### ISSUE TITLE
Error if there is no comment in jira issue

### ISSUE THREAD

**Issue by trepel** [kpiwko/jira-miner#7] opened 2017-10-12 14:07 UTC
```
error:  TypeError: Cannot read property 'filter' of undefined
    at snapshotInTime (/home/trepel/jiraMiner/jira-miner/lib/db/client.js:36:31)
    at mapFunction (/home/trepel/jiraMiner/jira-miner/lib/db/client.js:93:18)
```

I didn't dig deep into it but at the first glance it seems it is due to no comment exists for the jira issue being processed. I locally workarounded it by wrapping the 
```
    copy.Comment = issue.Comment.filter(comment => {
      return moment(comment.lastUpdated).isBefore(date)
    })
```
call into `if (issue.Comment)` { ...} statement. 

I am not 100% sure this is proper workaround though.

**Comment by kpiwko** [comment] 2019-09-05 14:36
Is this still valid @trepel ?

**Comment by trepel** [comment] 2019-09-13 12:36
Not sure, I didn't use jira-miner recently. The piece of code seems to be there unchanged though:
https://github.com/kpiwko/jira-miner/blob/master/src/lib/db/LocalJiraDB.ts#L40-L43

I have noticed you refactored to typescript, not sure if that could have fixed the issue (using an empty array instead of `undefined` or something like that).

**Comment by kpiwko** [comment] 2019-09-17 16:53
Closing, I was not able to reproduce the issue.

https://github.com/kpiwko/jira-miner/pull/10

**Closed by kpiwko** 2019-09-17 16:53 UTC
